spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix
server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://user:snlan@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}