security:
  basic:
    enabled: true
  user:
    name: user
    password: snlan
server:
  port: 8761
eureka:
  client:
    healthcheck:
      enable: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:snlan@localhost:8761/eureka